name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt
      
      - name: Deploy multi-task workflow wids-prod-telco-churn-train-deploy-inference-workflow [prod environment]
        run: |
          dbx deploy -e prod --deployment-file conf/deployment.yml wids-prod-telco-churn-train-deploy-inference-workflow
        
      - name: Launch model training, deployment and inference workflow [prod environment]
        run: |
          dbx launch -e prod wids-prod-telco-churn-train-deploy-inference-workflow

    